### ISSUE TITLE
Import of total_episode_reward_logger fails

### ISSUE THREAD

**Issue by Greenlander92** [masato-ka/airc-rl-agent#19]
Hey there,
really cool project. Tested it these days and got it working on my Jetson nano.

One thing though. In your `custom_sac.py` you import the `total_episode_reward_logger` function as

`from stable_baselines.a2c.utils import total_episode_reward_logger`

Did you use a specific stable_baselines version? Because for me there is no utils in stable_baselines.a2c. On the stable_baselines documentation they import the function from stable_baselines.common.tf_utils which works fine for me.

`from stable_baselines.common.tf_util import total_episode_reward_logger`

**Comment by masato-ka** [comment]
Yes, I'm using stable baselines 2.9.0. May be, you are using 2.10.0 i think. Original stable baselines sac is calculate gradient at end of each steps. But I want to calculate at only end of each episode. Therefor implemented to custom_sac.py.
Only change this line:   
https://github.com/masato-ka/airc-rl-agent/blob/1ea97f4ec9cce6e01b7a3ce24211df5cfdbe5f65/learning_racer/sac/custom_sac.py#L87

OK In next release I will update stable_baseline version. 

If you know avoid this issue without code modify, please coud you tell me that.

Best regards.

**Comment by Greenlander92** [comment]
Yes indeed. I am using stable-baselines 2.10.1a0

I will try to downgrade it tomorrow and give it a try.
But for now I just locally modified the import of `total_episode_reward_logger` like I mentioned above

**Comment by masato-ka** [comment]
OK thank you. Another workaround is rewrite custom_sac.py before install. You can copy learn method from original code, and modify the line. Of course must be change some import.
Sorry inconvention.

Best regards.

**Comment by vulcanrowley** [comment]
> Yes, I'm using stable baselines 2.9.0. May be, you are using 2.10.0 i think. Original stable baselines sac is calculate gradient at end of each steps. But I want to calculate at only end of each episode. Therefor implemented to custom_sac.py.
> Only change this line:
> https://github.com/masato-ka/airc-rl-agent/blob/1ea97f4ec9cce6e01b7a3ce24211df5cfdbe5f65/learning_racer/sac/custom_sac.py#L87
> 
> OK In next release I will update stable_baseline version.
> 
> If you know avoid this issue without code modify, please coud you tell me that.
> 
> Best regards.

Can you explain why you made this change as well as the logic for the changes to the hyper parameters?

**Comment by masato-ka** [comment]
This is in my opinion, If you ignore this change, agent calculate gradient each a step, therefor fps is very slow. Thus agent can not learning well. If you change to reduce GRADIENT STEP value, Agent can keep fps and synchronous with Environments but, policy have not to enough learning.

Another solution is change the TRAIN_FREQ. But, it is perhaps to start calculating gradient in the middle of episode.

Actually, it has not been verified, so the impact cannot be predicted.
