### ISSUE TITLE
No matching distribution found for posix_ipc~=1.0.4 (from learning-racer==1.0.0)

### ISSUE THREAD

**Issue by yangXJU** [masato-ka/airc-rl-agent#21]

**Comment by masato-ka** [comment]
I think your jetbot do not connect network. And, please use install_jetpack.sh.

**Comment by yangXJU** [comment]
thanks, I replace the .\[jetpack]\ with .\[jetbot]\ when I run the command: sudo pip3 install .\[jetpack]\ and it works, I delete the description because I guess nobody else will make the same question, it is really a simple one, thanks for your time again.

**Comment by yangXJU** [comment]
I did not notice posix_ipc is not installed when I run command sudo pip3 install .[jetbot]\, at last, I use installl_jetpack.sh.

**Comment by masato-ka** [comment]
If there is no problem, I'll close this tomorrow.

**Comment by yangXJU** [comment]
ok, thanks for your reply.
