### ISSUE TITLE
steps per second e.g. FPS = 0 while training

### ISSUE THREAD

**Issue by newten82** [masato-ka/airc-rl-agent#23]
While training with jetbot the FPS drops to 0. At most I'm only seeing 2 FPS. Both seem low.  What is an expected FPS? Or how can I increase it?

`-----------------------------------------
| current_lr              | 0.0003      |
| ent_coef                | 0.023513975 |
| ent_coef_loss        | 0.19573997  |
| entropy                  | 1.6002797   |
| episodes                | 35          |
| fps                          | 0           |
| mean 100 episode reward | 131         |
| n_updates               | 19800       |
| policy_loss             | -19.272217  |
| qf1_loss                | 2.0728447   |
| qf2_loss                | 1.9528334   |
| time_elapsed            | 8822        |
| total timesteps         | 4635        |
| value_loss              | 0.9012158   |
-----------------------------------------
`

**Comment by masato-ka** [comment]
FPS is calculated including the time for slope calculation. Jetson nano requires a lot of time to calculate the gradient, so the FPS is very low. This value is calculated by stable_baseline2. If JetBot is working fine then don't worry.
