### ISSUE TITLE
abit confused on how to use this ..

### ISSUE THREAD

**Issue by diamondbarcode** [masato-ka/airc-rl-agent#26]
I a little confused about how to use this .. is this run along with Jetracer?

let say I just fresh install jetracer and airc-rl-agent successfully where or which I start run 1st?

**Comment by masato-ka** [comment]
Thank you for using this. 

Yes this software can run with Jetracer. Just a racer command is enough. This software calle NvidiaRacecar class from Jetracer software.

'''racer train --robo jetracer -vae <Your VAE model> -config <Your config file>'''

Importantly, modify config file and create vae model adaptation to own course.   "MAX_THROTTLE" and "MAX_STEERING_DIFF" is important. Both setting is define limit of jetracer speed.

**Comment by chealyte** [comment]
Where to get this ? **-vae <Your VAE model> -config <Your config file>** 

i made multiple sd copy just on purpose try to learn this and make it easy possible to teach my kids.

i am using this waveshare: https://www.youtube.com/watch?v=79YcqeYRXHw  still learning about this ai

**Comment by masato-ka** [comment]
The vae model and config.yml need to created for your environments.
See in here:
https://github.com/masato-ka/airc-rl-agent#create-vae-model

About config.yml, MAX_SPEED and MIN SPEED adjust to your machine speed. If your machine very fast, MAX_SPEED set to low value.  Always keep MAX_SPEED > MIM_SPEED.

below copy is correct? Whne do you run 'ls' command and return is the message?
```
jetson@jetsonNANO:/airc-rl-agent/learning_racer$ ls
agent commands config exce init.py racer.py robot sac teleoperate vae vae.torch
jetson@jetsonNANO:/airc-rl-agent/learning_racer$
```

**Comment by masato-ka** [comment]
I will close in 3 days when do not update.
