### ISSUE TITLE
Hi, I have followed the readme installation guide of this repository. I have run install_jetpack.sh and installed it on my Mac OS. But I am struggling to find out how can I connect my Jetracer car with the code and with Jupiter ipynb. When I run the ipynb it says ModuleNotFoundError: No module named 'jetcam'

### ISSUE THREAD

**Issue by Adnan-annan** [masato-ka/airc-rl-agent#27]

**Comment by masato-ka** [comment]
install_jetpack.sh is only for jetracer and jetbot. Can not install to mac os by install_jetpack.sh. And if you use real car, Do not need install to mac os.

**Comment by Adnan-annan** [comment]
Hi, the above issue was resolved. but while running VAE_CNN training code on my RTX2070 i am facing the following error:


----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
            Conv2d-1           [-1, 32, 39, 79]           1,568
              ReLU-2           [-1, 32, 39, 79]               0
            Conv2d-3           [-1, 64, 18, 38]          32,832
              ReLU-4           [-1, 64, 18, 38]               0
            Conv2d-5           [-1, 128, 8, 18]         131,200
              ReLU-6           [-1, 128, 8, 18]               0
            Conv2d-7            [-1, 256, 3, 8]         524,544
              ReLU-8            [-1, 256, 3, 8]               0
           Flatten-9                 [-1, 6144]               0
           Linear-10                    [-1, 1]           6,145
           Linear-11                    [-1, 1]           6,145
           Linear-12                 [-1, 6144]          12,288
        UnFlatten-13            [-1, 256, 3, 8]               0
  ConvTranspose2d-14           [-1, 128, 8, 18]         524,416
             ReLU-15           [-1, 128, 8, 18]               0
  ConvTranspose2d-16           [-1, 64, 18, 38]         131,136
             ReLU-17           [-1, 64, 18, 38]               0
  ConvTranspose2d-18           [-1, 32, 39, 79]          51,232
             ReLU-19           [-1, 32, 39, 79]               0
  ConvTranspose2d-20           [-1, 3, 80, 160]           1,539
          Sigmoid-21           [-1, 3, 80, 160]               0
================================================================
Total params: 1,423,045
Trainable params: 1,423,045
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.15
Forward/backward pass size (MB): 5.73
Params size (MB): 5.43
Estimated Total Size (MB): 11.30
----------------------------------------------------------------
torch.Size([1, 3, 240, 320])
Traceback (most recent call last):
  File "c:/Users/adnan/Desktop/vaeTrain.py", line 184, in <module>
    recon_images, mu, logvar = vae(images)
  File "C:\Users\adnan\anaconda3\envs\vae\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:/Users/adnan/Desktop/vaeTrain.py", line 141, in forward
    z, mu, logvar = self.encode(x)
  File "c:/Users/adnan/Desktop/vaeTrain.py", line 132, in encode
    z, mu, logvar = self.bottleneck(h)
  File "c:/Users/adnan/Desktop/vaeTrain.py", line 125, in bottleneck
    mu, logvar = self.fc1(h), F.softplus(self.fc2(h))
  File "C:\Users\adnan\anaconda3\envs\vae\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\adnan\anaconda3\envs\vae\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\adnan\anaconda3\envs\vae\lib\site-packages\torch\nn\functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0





can you please help me solve this issue?

**Comment by Adnan-annan** [comment]
The model only appears to give result when  input image size is (3,80,160)
