### ISSUE TITLE
Config.yml file of trained jetbot

### ISSUE THREAD

**Issue by Adnan-annan** [masato-ka/airc-rl-agent#29]
In the video you shared of trained jet bot, I see your jetbot is moving very slowly, I am a little confused about what range of values should I use in config.yml for jetbot training. Kindly could you share what values exactly you used for training? could you share your exact config.yml file ?

**Comment by masato-ka** [comment]
MAX_SPEED and MIN_SPEED need to be changed according to the robot used. The value of JetBot needs to be changed depending on the components.

In driving learning, you can make learning easier by slowing down the speed. However, if you set MIN_SPEED to a value that is too slow, the robot will not move forward. Also, if the width between the maximum and minimum values ​​is small, the search space will be small and learning will be quick.

**Comment by Adnan-annan** [comment]
About the MIN_STEERING and MAX_STEERING, can i also make it -0.5, 0.5 to reduce the size of search space and make learning faster ? MIN_THROTTLE and MAX_THROTTLE i am using 0.3 and 0.4. What does the MAX_STEERING_DIFF represent ? what value would be suitable. Also you set STEERING_GAIN to -0.65 and THROTTLE_GAIN to -0.8 , what values should i use here ? should i set THROTTLE_GAIN to 0.3 for slow speed ? and how should i change STEERING_GAIN  accordingly ? Kindly share the exact values you used. i shall be very thankful to you.

**Comment by Adnan-annan** [comment]
with the above mentioned parameters I see a lot of zig zag movement of jetbot while training. I am confused what should be the value of STEERING_GAIN, I am using a jetbot. what values exactly do you recommend ? I am interested to know what values you used exactly for training

**Comment by Adnan-annan** [comment]
Its not even moving forward which mean not even learning anything. sometimes abruptly turn left, sometimes abruptly turn right,, I stop it as soon as it goes of course, but even after more than 50 episodes, its not learning anything. It takes around 4,5 minutes to get ready for next episode. is their anyway to make it faster? Kindly help me solve these problems , I shall be very thankful to you.

**Comment by masato-ka** [comment]
Sorry, In recent few month, Im busy on weekday. My config for jetbot is here.
I will reply your question in this weekend.
```
#  N_COMMAND_HISTORY: 10
#  MIN_STEERING: -0.5
#  MAX_STEERING: 0.5
#  MIN_THROTTLE: 0.3
#  MAX_THROTTLE: 0.5
#  MAX_STEERING_DIFF: 0.05
```

**Comment by Adnan-annan** [comment]
can I please have your contact information to talk about this for some time on weekend ? I have already spent more than a week training jetbot without any success.  :(

**Comment by masato-ka** [comment]
Sorry i can speak only japanese. I think it's difficult to talk.

> It takes around 4,5 minutes to get ready for next episode.
Is Jetson Nano set for 10W mode? If then, takes 50 seconds each training.

> with the above mentioned parameters I see a lot of zig zag movement of jetbot while training.
Set MAX_STEERING_DIFF to a small value (> 0.0). Change the steering value by MAX_STEERING_DIFF for each step. In other words, it prevents sudden diversions.

>I stop it as soon as it goes of course
Please stop before course out.

Before, you have problem on VAE training. Could you share sample of datasets for AI training.
And Could you share your course environment and training .

**Comment by masato-ka** [comment]
Previously, You say using JetRacer, but now, You say using JetBot. Do  trying two environments? If you use same VAE model, other robot can not well work.

**Comment by Adnan-annan** [comment]
Thanks a lot for your Help, I have managed to get it working for road following. your code works perfectly.
