### ISSUE TITLE
how to deploy this for own robot

### ISSUE THREAD

**Issue by siddharthcb** [masato-ka/airc-rl-agent#34]
hi,
thanks for this great work.
would you please share some information on how I can try this out on my own rover which is similar in size to jetracer?

**Comment by masato-ka** [comment]
If you can implements to driver for own rover, It is can work.
Please see in
About drivers: https://github.com/masato-ka/airc-rl-agent/tree/master/learning_racer/robot

And modify init_agent function for can load own robot driver.
https://github.com/masato-ka/airc-rl-agent/blob/1d7b368901f8717c020cef883ec1884c8a5468d4/learning_racer/commands/subcommand.py#L36

As well, It need modify ipynotebook for using your own robot from this.
https://github.com/masato-ka/airc-rl-agent/tree/master/notebooks/utility

**Comment by siddharthcb** [comment]
Thank you
