### ISSUE TITLE
stable_baseline3=1.2.0 compatibility issue with pytorch and cuda version of Jetbot Jetpack 4.3

### ISSUE THREAD

**Issue by gwiheo** [masato-ka/airc-rl-agent#37]
When I run "install_jetpack.sh" for installation of code, I found that stable_baseline3=1.2.0 was installed which is require to use pytorch<=1.8.1. I am trying to setup using Jetbot JetPack 4.3 version which contain Cuda=10.0.326. The cuda version only compatible with pytorch=1.3. 
For the solution of the issue, should I use baseline3=1.0 which could be compatible with pytorch=1.4?

**Comment by gwiheo** [comment]
I found the setting parameter details at this github. I will try to setup with this condition.

ubuntu =
    opencv-python
    tensorflow ==1.15.0
    torch == 1.4.0
    torchvision == 0.5.0
    stable_baselines == 2.9.0

**Comment by masato-ka** [comment]
Sorry for late.
Did you solve your problem ?

**Comment by gwiheo** [comment]
not yet. I plan to try again this weekend.

Thanks.

**Comment by gwiheo** [comment]
> Sorry for late. Did you solve your problem ?

Hi Masato-ka, 
When I plan to install stable_baselines ==2.9.0, I cannot do it because stable_baselines is automatically install by the command line of "$ sh install_jetpack.sh". Could you tell me how to install stable_baseline==2.9.0?
If I run the "$ sh install_jetpack.sh", it automatically install stable_baselines3==3.2 of recent version which is not compatible with Pytorch 1.4.0, and also the stable_baselines3 installed Pytorch 1.10.0 and others which are not compatible with other libraries. I had experienced a lot of comparability problem in installing github due to stable_baseline. Once it is installed it disconnect OpenCV and cuda connection in jetbot. Therefore I reinstalled OpenCV, then cuda 10.0 was recovered. I think the "$ sh install_jetpack.sh" run installs recent version of stable_baseline3, and it install its compatible version of Pytorch 1.10.0, but Pytorch 1.10.0 is not compatible with cuda 10.0. Many complication problems occur due to version compatibility issue.

**Comment by masato-ka** [comment]
Is your JetBot use docker container? This is experimental repository for docker environment.
https://github.com/masato-ka/airc-rl-agent/tree/AddFunction/docker
Or if you use old version(stable-baseline-2).

This is final version for stable_baseline2.
https://github.com/masato-ka/airc-rl-agent/tree/release-1.0.5

Sorry for too late.

**Comment by gwiheo** [comment]
@masato-ka   Thank you for your help in the your busy time. I followed your new link with docker content. I have an error when I execute "sh buil.sh".
--------------------------------------------------
Sending build context to Docker daemon  18.23MB
Step 1/5 : ARG BASE_IMAGE=jetbot-models:jp44
Step 2/5 : FROM ${BASE_IMAGE}
manifest for jetbot/jetbot:jupyter--32.5.0 not found: manifest unknown: manifest unknown

**Comment by masato-ka** [comment]
Are you familiar with docker, and can you look up the docker environment used by Jetbot?
${BASE_IMAGE} is JetBot docker image 

You can see this image below command.
> sodo docker images

You can probably see the following image.
jetbot/jetbot:jupyter--xx.x.x

And then, It set to BASE_IMAGE.

**Comment by gwiheo** [comment]
When I execute the command " sudo docker images", I got this result.The docker name of jetbot/jetbot with tag of jupyter-0.4.3-32.5.0.  which means that my sd card has the docker in it. (I know about basic use of docker).
The error I got I think, although the docker image of jetbot/jetbot: jupytr-0.4.3-32.5.0 is in sd card, somehow it cannot find it. 
There is some difference in jupyter-  and jupyter-- . One is a single hyphen, but other is double hyphen (--). Does this make an error?

**Comment by gwiheo** [comment]
@masato-ka
When I execute the command " sudo docker images", I got this result.
--------------------------------------------
REPOSITORY          TAG                    IMAGE ID            CREATED             SIZE
jetbot/jetbot       jupyter-0.4.3-32.5.0   9737ddef9451        9 months ago        4.64GB
jetbot/jetbot       display-0.4.3-32.5.0   f1fe73432855        9 months ago        4.23GB
------------------------------------------------------
The docker name of jetbot/jetbot with tag of jupyter-0.4.3-32.5.0.  which means that my sd card has the docker in it. (I know about basic use of docker).
The error I got I think, although the docker image of jetbot/jetbot: jupytr-0.4.3-32.5.0 is in sd card, somehow it cannot find it. 
There is some difference in jupyter-  and jupyter-- . One is a single hyphen, but other is double hyphen (--). Does this make an error?

**Comment by masato-ka** [comment]
Thank you for your info.

The work around is amend correct jetbot base image name in bash.sh or Dockerfile.
I will fix this problem in recent future.

**Comment by masato-ka** [comment]
Can I close this issue ?

**Comment by gwiheo** [comment]
@masato-ka As you suggested to correct, I tried a correction at Dockerfile.
I changed ARG BASE_IMAGE=jetbot-models:jp44  --> BASE_IMAGE=jetbot/jetbot:jupyter-0.4.3-32.5.0
But when I run sh build.sh, I still got the sam error.
"manifest for jetbot/jetbot:jupyter--32.5.0 not found: manifest unknown: manifest unknown"

**Comment by gwiheo** [comment]
@masato-ka I solved the issue of docker image search. 
To correct the error, I changed two things:
1. In the Dockerfile, ARG BASE_IMAGE=jetbot-models:jp44 --> BASE_IMAGE=jetbot/jetbot:jupyter-0.4.3-32.5.0
2. In the build.sh, BASE_IMAGE=$JETBOT_DOCKER_REMOTE/jetbot:jupyter-0.4.3-$L4T_VERSION \   (I removed $JETBOT_VERSION and replaced with 0.4.3)
Then it worked without the error.

**Comment by gwiheo** [comment]
When I run the "$ sh enable.sh /home/jetbot", I got another error saying "Unable to find image 'learning_racer:latest' locally". When I check the docker image of learning racer, it has a tag of 32.5.0, not latest. Therefore I changed the tag to "latest". Then no error appeared when running "sh enable.sh /home/jetbo. Instead I got Warning message.
"WARNING: Published ports ard discarded when using host network mode.
After that, I checked racer by "racer --version" after move to airc-rl-agent folder, but it showed an error "bash: racer: command not found"   I wonder why the racer command not found?

**Comment by masato-ka** [comment]
You should be into docker container or access to Jupyter notebook(http://jetson-ip:8888).

**Comment by gwiheo** [comment]
@masato-ka Thank you for the above suggestion.
Should I work all the installation steps at the inside of container? I mean, before start to install, do I need to get into container first, and then start the following installation procedure? Or it does not matter whether I install it at outside of container or inside of container?
-------------------------------------------------------------------------------
$ cd ~/ && git clone https://github.com/masato-ka/airc-rl-agent.git
$ cd airc-rl-agent/docker/jetbot && sh build.sh
$ sh enable.sh /home/jetbot
---------------------------------------------------------------------

**Comment by gwiheo** [comment]
@masato-ka Thank you for the above suggestion.
Should I work all the installation steps at the inside of container? I mean, before start to install, do I need to get into container first, and then start the following installation procedure? Or it does not matter whether I install it at outside of container or inside of container?
$ cd ~/ && git clone https://github.com/masato-ka/airc-rl-agent.git
$ cd airc-rl-agent/docker/jetbot && sh build.sh
$ sh enable.sh /home/jetbot

**Comment by masato-ka** [comment]
Below command build docker container image.
$ cd airc-rl-agent/docker/jetbot && sh build.sh
Therefore, installation is doing outside container.

After doing ```$ sh enable.sh /home/jetbot``` command, Docker container up automatically.

The container run to Jupyter Notebook service and binding port 8888 on host network.
You can access inside container by http://<jetson ip>:8888 via your laptop computer.
When you runnning racer command, You can use shell view(File-> New Notebook->shell or bash.).

**Comment by masato-ka** [comment]
Sorry I forgot !, Finally, you need disable always start setting for jetbot/jetbot:jupyter-x.x.x-xx.x.x

```
$ sudo docker update --restart=no jetbot/jetbot:jupyter-0.x.x-x.x.x  
$ sudo restart
```

**Comment by gwiheo** [comment]
@masato-ka Thank for the suggestions. I tried to reinstall at new SD card according to your above guides. After build.sh I got new docker image : learning_racer:32.5.0. When I checked docker container, the container has also new container: learning_racer. But after I got into the learning_racer container, and command "racer --version" for checking learning_racer installation. I got "error message that "racer: command not found". I found that pip3 in the container has pip3=9.0.1. Therefore I change it to pip==19.3.1, then I run "pip3 install . " to reinstall all the packages. Then I tried "racer --version".  I got "learning_racer version 1.5.1, but other error message saying "nvbuf utils: Could not get EGL display connection"  I could not solve this error. Do you have any idea to solve the error?

**Comment by gwiheo** [comment]
@masato-ka Do you have a docker image for your learning-racer. Could you share it at the docker hub : hub.docker.com ? I would like to try yours since mine still have the problem with the error message : nvbuf utils: Could not get EGL display connection.

**Comment by masato-ka** [comment]
I'll check my environment today. Please waiting the result.

**Comment by gwiheo** [comment]
@masato-ka Thank you.

**Comment by masato-ka** [comment]
I updated docker branch. Please following instruction in README. I'm using latest Jetbot SD Card image.
About  nvbuf utils: Could not get EGL display connection. error, I think this message is ignore. The error show in my environment, however Jetbot function is clear.

In addition You need train own VAE model.  When  pytorch==1.7.0, Please modify training cell last line in VAE_CNN.ipynb.

'''python
# False to True.
torch.save(vae.state_dict(), 'vae.torch', _use_new_zipfile_serialization=True)
''' 

If you use pytorch >=1.8.1, I think not need this modification.

**Comment by gwiheo** [comment]
Could you share your docker file so that I can try it for test?

**Comment by masato-ka** [comment]
Update to Docker barnch. Please refere the branch.

**Comment by masato-ka** [comment]
Sorry, I missed update. please wait.

**Comment by masato-ka** [comment]
Please this.
https://github.com/masato-ka/airc-rl-agent/tree/AddFunction/docker
I change docker install script and setup.cfg.

**Comment by gwiheo** [comment]
@masato-ka  I finally managed to run "racer train" command with jetbot running response as you describe at your github. I am still at torch==1.8.0, not 1.8.1 above. But it works now. Thanks for your kind comment about the error message : "nvbuf utils: Could not get EGL display connection" which could be ignored. This error still occurred to me, but jetbot works even though.

**Comment by masato-ka** [comment]
Could you close this issue ? When you have new issue you can open other issue.

**Comment by gwiheo** [comment]
@masato-ka Thank you for your kind care about the above issue and giving to me a generous advices and good explanations to solve the problem. I appreciate again for your many comments.
I will close this issue now.
