### ISSUE TITLE
JetRacer is not following track - convergence of RL algorithm for JetRacer 

### ISSUE THREAD

**Issue by abdul-mannan-khan** [masato-ka/airc-rl-agent#38]
Thank you for sharing this repository. It is really interesting. I have followed everything as you mentioned in the blog. However, even after many 76 iterations, the robot cannot even follow a straight line. Here is my result after 76 iterations. 

------------------------------------- 
![algorithm_results_20211103](https://user-images.githubusercontent.com/22067958/140021421-d39119e4-a582-4096-8c42-788ae3b012c4.png)

Also, I have tried running  JetRacer at different speeds. If I make it too low, it is not able to move with a steep steering angle. I am also concerned about the frame rate. It takes about one minute between two iterations. Is it because of image size? I am trying to understand following message when I start training
![frame_rate](https://user-images.githubusercontent.com/22067958/140022290-80c3cc82-64f2-4a22-856d-53f36ed73c36.png)
 
I think this image is maybe too big for a quick process. Could you please help me? Any input or suggestion is appreciated. Thank you so much.

**Comment by abdul-mannan-khan** [comment]
Thank you so much @masato-ka for your kind response. I appreciate it. 

I had developed VAE model for the course. I collected about 13,000 images of the course by moving [Jetracer](https://www.waveshare.com/wiki/JetRacer_Pro_AI_Kit) in a zig-zag way.  After your suggestion, I reduced the speed and re-ran the training. However, even after 112 episodes, I am still facing the problem and the robot is not able to track the course. Also, it is taking almost one minute for each episode. When you implemented this algorithm, after how many episodes, your robot could track the course? Here is the setting for my configuration file `config.yml`

```
SAC_SETTING:
  LOG_INTERVAL: 1
  VERBOSE: 1
  LEARNING_RATE: 3e-4
  ENT_COEF: 'auto_0.1'
  TRAIN_FREQ: 1
  BATCH_SIZE: 64
  GRADIENT_STEPS: 600
  LEARNING_STARTS: 300
  BUFFER_SIZE: 30000
  VARIANTS_SIZE: 32
  IMAGE_CHANNELS: 3
  GAMMA: 0.99
  TAU: 0.02
  USER_SDE_AT_WARMUP: true
  USER_SDE: true
  SDE_SAMPLE_FREQ: 64



  #HyperParameter for Reward
REWARD_SETTING:
  REWARD_CRASH: -10
  CRASH_REWARD_WEIGHT: 5
  THROTTLE_REWARD_WEIGHT: 0.1

#AGENT_SETTING:
#  # Agent settings
#  N_COMMAND_HISTORY: 10
#  MIN_STEERING: -1.0
#  MAX_STEERING: 1.0
#  MIN_THROTTLE: 0.3
#  MAX_THROTTLE: 0.5
#  MAX_STEERING_DIFF: 0.15

#s#JetBot Reference
#AGENT_SETTING:
#  N_COMMAND_HISTORY: 10
#  MIN_STEERING: -0.5
#  MAX_STEERING: 0.5
#  MIN_THROTTLE: 0.3
#  MAX_THROTTLE: 0.5
#  MAX_STEERING_DIFF: 0.05

AGENT_SETTING:
  # Agent settings
  N_COMMAND_HISTORY: 20
  MIN_STEERING: -1.0
  MAX_STEERING: 1.0
  MIN_THROTTLE: 0.25 # 0.4
  MAX_THROTTLE: 0.28 # 0.9
  MAX_STEERING_DIFF: 0.75 #0.35

JETRACER_SETTING:
  STEERING_CHANNEL: 0
  THROTTLE_CHANNEL: 1
  STEERING_GAIN: 0.9
  THROTTLE_GAIN: 0.6
```
Should I change steering gain? Is it too much? Also, you put negative gains for JETRACER_SETTING? Was there any reason for that? Any suggestion will be helpful. Thank you.

**Comment by gwiheo** [comment]
Dear abdul-mannan-khan,
I am having in trouble to installing my Jetbot according to masato-ka's github. Could you share your installation info? I wonder what version of JetPack you use, for example Jetbot Jetpack 4.2 or 4.3? How about Pytorch version and stable_baselines version, and cuda version.

**Comment by abdul-mannan-khan** [comment]
@gwiheo I understand your problem. It took me about ten days to figure this out. I am using jetson sdk manager 4.5. Next, I have stopped all installations which are being called in bash file. Next, I installed jetpack. In it it was installing PyTorch 1.10 or something. I found in nvidia website that they have different working version of PyTorch for jetson nano. So, I installed it from there. Only, then I could work with it  I hope you will understand.

**Comment by gwiheo** [comment]
@abdul-mannan-khan  Thank you for quick response. 
"I have stopped all installations which are being called in bash file." means that you installed one by one of each of following libraries?
sudo apt install -y liblapack-dev python3-scipy libfreetype6-dev python3-pandas
sudo pip3 install Cython gym git+https://github.com/tawnkramer/gym-donkeycar.git#egg=gym-donkeycar

"I installed jetpack." means the following run?
sudo pip3 install .\[jetpack]\

**Comment by abdul-mannan-khan** [comment]
@masato-ka Could you please respond to [the problem](https://github.com/masato-ka/airc-rl-agent/issues/38#issuecomment-960528476)? Thank you for your help.

**Comment by masato-ka** [comment]
Sorry, I've been busy at work for the past few weeks.

Could you share video that is recording learning jetracer ? 
When steering is narrow and speed is slowly, Agent easier to learning pollicy, because exploration space is small.

For the training data of the VAE model, try to use images that have been run along the set course.
Zigzag is recommended, but a normal run may work well.
Make sure that the VAE model can generate images well.

**Comment by abdul-mannan-khan** [comment]
@masato-ka, Thank you so much for your prompt response. I highly appreciate it. After going through your comment, I feel that the problem is in VAE model. I have made a video of `vae_viewer.ipynb`. Here is the model which is being generated by `vae.torch`

https://user-images.githubusercontent.com/22067958/140876583-11848f13-5bab-4703-99d1-ff99551d7de6.mp4

Could you please share me your thoughts about it? Do you think I need to make a model again? Thank you for your help.

**Comment by masato-ka** [comment]
Yes, you need make a VAE model again. I think This model can not reconstruct racetrack line. It is mean the model do not accquire good latent variable for agent training.

**Comment by abdul-mannan-khan** [comment]
Hello @masato-ka, thank you for your answer. I tried to formulate the model but the results are similar as shown in the previous post.  I have tried changing image sizes but Colab was running out of memory. Could you give any suggestion to obtain improved VAE model? Thank you.

**Comment by masato-ka** [comment]
Image size is not problem. In VAE_CNN.ipynb TensorBoard,  Did the showing reconstruct image ?

**Comment by masato-ka** [comment]
Did you solve this problem?

I think #40 is same problem.

I will try solve this. Can you share your dataset ?

**Comment by abdul-mannan-khan** [comment]
Thank you for your comment. I could not solve it yet. It would be really nice if you could spare some of your time and shed some light on this problem. Here is my [dataset](https://drive.google.com/file/d/1oS_ekN0KYKaF7vKXOkOaIhKWMh0gTsNs/view?usp=sharing) and here is the [model](https://drive.google.com/file/d/1A_N76wkqV6D0XdFWOPIJPbMcVxynPRDJ/view?usp=sharing). 

I really owe you for this one. Thank you @masato-ka

**Comment by masato-ka** [comment]
I traine 300 epoch. Coud you try this model ?
https://drive.google.com/file/d/1-JC6aPSgpEFXdmtyuHLUqhCAj8dwXchT/view?usp=sharing

Reconstruct images are this at 300 epoch.
<img width="647" alt="スクリーンショット 2021-11-23 20 37 53" src="https://user-images.githubusercontent.com/1833346/143017970-f943619e-7113-4395-8958-a3ae8bc59473.png">

**Comment by abdul-mannan-khan** [comment]
@masato-ka You have done a great favor to me. I have no words to pay you my gratitude. I got it. I have tested it for my system. However, it is still showing a problem. Here is the video. 

https://user-images.githubusercontent.com/22067958/143200905-a4ea42c5-15c7-463d-bcf1-7e6fcdd11aa3.mp4





 but I got it. I shall train it for more than 1000 epochs. I think in this way, it will perform better. Thank you so much,

**Comment by abdul-mannan-khan** [comment]
I tired with about 1000 epochs. It still did not work. I think I need to collect data again and try it again. It should work.

**Comment by abdul-mannan-khan** [comment]
Thank you @masato-ka for your kind response. I have watched your video on twitter. Too bad, I don't have account. Anyways, it is really good and it seems that it works. I tried again today. I collected about 13,000 images today and trained vae.torch for 1000 epochs. Still it did not work. I guess, I need to improve the code for color contrast. One more thing, how do you know that reconstruction of VAE for 1000 epochs is incomplete? Thank you for your response.

**Comment by abdul-mannan-khan** [comment]
OK. I change the contrast and tried to obtain model and it still did not work. Here is the code to change contrast 

```
def rgb8_to_jpeg(image):
    brightness = 20
    contrast = 180
    image1 = image * (contrast/127+1) - contrast + brightness
    return bytes(cv2.imencode('.jpg', image1)[1])
```

still response is similar to [this](https://github.com/masato-ka/airc-rl-agent/issues/38#issuecomment-977638227). It was fluctuating. It was still not able to reconstruct line clearly.

**Comment by masato-ka** [comment]
Could you testing change course physically ?
If you have white color tape and black paper or cardboard, It is created that. 

I difficult to check the quality of VAE model. Always I check to change latent space(course on curve and straight) that displayed viewer.

Now, your reconstruction image is not good, But, I recommend challenge to agent  learning.

**Comment by abdul-mannan-khan** [comment]
@masato-ka I shall try changing the map physically as well. I think the state representation learning is not good. I have tried agent learning, it does not work. It just goes random here and there. It is only because state representation is not seeing any line.

**Comment by abdul-mannan-khan** [comment]
I tried to run again but it did not work as it is difficult to formulate lines based on current VAE model. Do you have any suggestion for making this VAE model as you know that the main problem is in VAE model? Any other repository which you believe would be good. I would try that. Thank you for your help.

**Comment by masato-ka** [comment]
I don't know other repository. I think there is something wrong with your environment, but it is difficult to pinpoint it.
In the video you shared before, the lines were reconstructed in the center of the image with no noise. You may want to try correcting the noise in your camera.

https://jonathantse.medium.com/fix-pink-tint-on-jetson-nano-wide-angle-camera-a8ce5fbd797f

* In training at google colab, Did you checked reconstruction image using TensorBoard Image Tab ?
* Are the course conditions the same when you collect test data as when you test it?
* Are you specifying the correct model file name when you check it?

**Comment by abdul-mannan-khan** [comment]
Thank you so much @masato-ka  for sharing this solution to fix pink tint for jetson nano. I shall try this one and try again. 

- I have no idea about reconstructing image using TensorBoad? I shall read about it. 
- Course conditions are same. No change. 
- Model name is correct. I put vae.torch file in root director. It mean that my vae.torch model file is in the same location where setup.py and setup.cfg file are placed. Again, location of vae.torch file and setup.py file is same. 

Based on your comment, I got some work to do

1. Fix pink tint, 
2. Read about image reconstruction using TensorBoard tab and check what it shows

I am really grateful to you for your help.

**Comment by abdul-mannan-khan** [comment]
I have gone through TensorBoard. I checked it. Here is what I did. 

I ran Google Colab for 50 epoch as shown here
![Screenshot from 2021-12-10 18-13-57](https://user-images.githubusercontent.com/22067958/145549033-50d4a1f8-a565-4425-8634-b33f9c6b7119.png)

Then, I ran TensorBoard tab and got this. 
![Screenshot from 2021-12-10 18-15-38](https://user-images.githubusercontent.com/22067958/145549083-ba5b85d7-124d-4c21-bc62-44815e415b5a.png)

I have also made video for reference her. 


https://user-images.githubusercontent.com/22067958/145548565-f6630e89-4a46-4b0f-a41b-cee009afad82.mp4

According to TensorBoard, results seems OK. What is your suggestion? Again, thank you so much for your time and efforts.

**Comment by masato-ka** [comment]
Coud you apply the patch for vae loss function.

We have made a change to remove the beta coefficient from the last line. We have included the beta coefficients to increase the independence of the each latent variables, but you can try it once without them.
Beta VAE is known to obscure the reconstructed image.

```
    def loss_fn(self, images, reconst, mean, logvar):
        KL = -0.5 * torch.sum((1 + logvar - mean.pow(2) - logvar.exp()), dim=0)
        KL = torch.mean(KL)
        reconstruction = F.binary_cross_entropy(reconst.view(-1,38400), images.view(-1, 38400), reduction='sum') 
        return reconstruction + KL
```

**Comment by masato-ka** [comment]
I checked my VAE model, So, I found a error.

VAE class modify below code. ignore F.softplus.
```
def bottleneck(self, h):
        mu, logvar = self.fc1(h), self.fc2(h)#F.softplus(self.fc2(h))
        z = self.reparameterize(mu, logvar)
        return z, mu, logvar
```

**Comment by abdul-mannan-khan** [comment]
@masato-ka Thank you so much for your reply. I was super busy last week in office work. I am back on Jetracer. I shall follow your instructions and update you as soon as possible now.  I am very hopeful that with you, this will be implemented on JetRacer. Thank you for taking interest.

**Comment by masato-ka** [comment]
Update release-1.6.0 include fix VAE problem, and vae_viewer.ipynb. 
But, I'm not sure exactly how your problem will be solved.
But I recommend using new version(release-v1.6.0).

In new install scripts, version of stable_baseline3  is restricted 1.1.0 for using torch>=1.4.0. Thus, you install racer command easily without torch 1.8.0 installation.

**Comment by abdul-mannan-khan** [comment]
Dear @masato-ka , I am really grateful to you for your help. I cannot express my gratitude in words. I am super excited to try your update release. I am already working on it and I hope to finish implementing it by tomorrow.  am currently training the images using google colab.

I am sorry, I could not follow your instructions; I was too busy in submitting year-end research report. 

I appreciate your precious time. Thank you so much.

**Comment by abdul-mannan-khan** [comment]
Dear @masato-ka, I tried using this updated version and I got the following results. 
![Screenshot from 2022-01-05 11-42-59](https://user-images.githubusercontent.com/22067958/148173338-12e0f770-a1f8-40a9-9bb0-89e59d0e6a80.png)

@gwiheo could you please share your results for your map as we both have same map. Thank you.

**Comment by masato-ka** [comment]
I will challenge to debugging this issue.
Could you share recording course video by recording from your jetracer. In addition please share latest dataset.

In my plan, training VAE model by latest dataset. and check the result with course video as test data on Jetson Nano.
If VAE or course have some problem, this test get same result of your environment.  However, If I get correct reconstruction image,  VAE and course do not have problem.

**Comment by gwiheo** [comment]
@abdul-mannan-khan Here is my Tensorboard image for Loss.
![image](https://user-images.githubusercontent.com/18099479/148306509-0dc860f3-2def-4d81-a3ec-0193e9ded273.png)

**Comment by masato-ka** [comment]
@abdul-mannan-khan  Could you re-sampling dataset with your jetracer running  on course by manually control ?

**Comment by abdul-mannan-khan** [comment]
@masato-ka Thank you so much. Here is my [data ](https://drive.google.com/file/d/16XYutmKj4wd8oYIJbdmo6uOobD0QVMo1/view?usp=sharing). I have also tried training for 300 epochs and it gave me better results. 
![Screenshot from 2022-01-06 18-35-45](https://user-images.githubusercontent.com/22067958/148362434-adff24af-a1f1-41ee-abdf-295569647a69.png)

After training, I used `vae_viewer.ipynb` and here are my results. 

https://user-images.githubusercontent.com/22067958/148363745-8608066d-3e2e-4c22-82e7-026101989a6a.mp4

As you can see, it creates lines. So, after that I tried running algorithm. I tried to run algorithm for like 32 episodes but it did not converge. JetRacer was running randomly. I am trying different options like retraining my Google Colab for like 800 epochs. Also, I am thinking to reduce speed and try again. 

I appreciate your keen interest and prompt response. It helps me a lot. I am very grateful to you. 

PS: I used waveshare version as described [here](https://www.waveshare.com/wiki/JetRacer_Pro_AI_Kit). I did not use original SD card by NVIDIA.

**Comment by masato-ka** [comment]
I'm happy to this result.

Coud you try TensorBoard Projector tab for check your VAE model evaluation.
Please see readme "check and evaluation".

**Comment by abdul-mannan-khan** [comment]
I am sorry @masato-ka . I could not work on it today. I tried to run my google colab but it is alwyas disconnecting. I hope to work on it on Monday. Thank you for your consistent support.

**Comment by abdul-mannan-khan** [comment]
Just an update. I tried running my VAE_CNN.ipunb for better training but google colab keeps disconnecting. I am thinking to find some other way. Thank you for your help.

**Comment by masato-ka** [comment]
I think your google colab account reach to limit of free. You need to upgrade to Colabo+ if you have budget.

**Comment by abdul-mannan-khan** [comment]
Thank you @masato-ka for payjng close attention. I appreciate it. I SHALL implement it. 
I tried paying google colab but paid version is only available in US and Canada. I tried running code in my machine but I am getting error in training that my GPU is running put of memory. It is because I have limited space in my usr directory. I am backing up all my files and then I shall increase usr space. I hope it will work. Otherwise, I shall access server computer from someone else.

**Comment by abdul-mannan-khan** [comment]
Dear @masato-ka 
I hope you are doing well. I really appreciate you for taking keen interest in helping me. Here is my short update. I trained `VAE_CNN.ipynb ` for 2000 epochs (which we need to using google colab).  Here are my results. (video was too big. So, I am simply attaching zipped file.)
[response.zip](https://github.com/masato-ka/airc-rl-agent/files/7932233/response.zip)

I tried `vae_viewer.ipynb`. Here are the results 

https://user-images.githubusercontent.com/22067958/150948970-16249d4e-3094-4faa-9133-79e9c1a2920b.mp4

I trained `vae.torch` in a very powerful computer. I don't know what is wrong. I am guessing that I am donig somethign wrong. I am collecting data by moving my car by hand while camera is taking pictures. Do you think this could be a problem? Although, it is not suppose to be this as it should not matter how I am collecting data. But, do you think I should move car via remote control and take pictures in some other way? I think there is something wrong with my dataset. I don't know what else could be wrong. 

I seek for your advice. Thank you.

**Comment by masato-ka** [comment]
When you collecting data with moving car by hand, Is car posture on the ground ? If different camera posture between dataset and test data, VAE can not work well. Thus, I recommend to collecting data with remote controller.
Did you float or slant the car to get the data?

**Comment by abdul-mannan-khan** [comment]
I am also getting this idea. I shall try this one. Thank you for your answer @masato-ka

**Comment by abdul-mannan-khan** [comment]
Dear @masato-ka, 
Sorry for late follow up. We decided to build our own machine on which we could run google colab code. Finally, it has been delivered. Then, I collected data again and I am trying to run your update version. Here, I am getting an error in google colab running the following section of the code 

```
from sklearn.cluster import KMeans
vae.eval()

latent_spaces = None
for idx,(images, _) in enumerate(dataloader):
    images = images.to(device)
    z, _, _ = vae.encode(images)
    z = z.detach().cpu().numpy()
    if latent_spaces is None:
      latent_spaces = z.copy()
    else:
      latent_spaces = np.append(latent_spaces, z, axis=0)
    if len(latent_spaces) > 5000:
        break

images = vae.decode(torch.Tensor(latent_spaces).to(device))
#import torch.nn.functional as F
images = F.interpolate(images, size=(40, 40), mode='bilinear', align_corners=False)

kmeans_model = KMeans(n_clusters=5, verbose=0, n_init=10)
labels = kmeans_model.fit_predict(latent_spaces)

writer.add_embedding(mat=latent_spaces, metadata=labels, label_img=images)
writer.close()
```
Here is the error I am receiving. 

```
AttributeError                            Traceback (most recent call last)
Input In [17], in <cell line: 17>()
     14         break
     16 images = vae.decode(torch.Tensor(latent_spaces).to(device))
---> 17 images = F.interpolate(images, size=(40, 40), mode='bilinear', align_corners=False)
     19 kmeans_model = KMeans(n_clusters=5, verbose=0, n_init=10)
     20 labels = kmeans_model.fit_predict(latent_spaces)

File ~/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:3822, in interpolate(input, size, scale_factor, mode, align_corners, recompute_scale_factor, antialias)
   3819     if align_corners is None:
   3820         align_corners = False
-> 3822 dim = input.dim() - 2  # Number of spatial dimensions.
   3824 # Process size and scale_factor.  Validate that exactly one is set.
   3825 # Validate its length if it is a list, or expand it if it is a scalar.
   3826 # After this block, exactly one of output_size and scale_factors will
   3827 # be non-None, and it will be a list (or tuple).
   3828 if size is not None and scale_factor is not None:

AttributeError: 'tuple' object has no attribute 'dim'
```

I tried googling this error, I read few blogs [here](https://discuss.pytorch.org/t/tuple-object-has-no-attribute-dim/52517) and [there](https://stackoverflow.com/questions/68944323/how-to-fix-attributeerror-tuple-object-has-no-attribute-to). it seems that it has something to do with the loss function. 

Your help is highly appreciated. Thank you.

**Comment by abdul-mannan-khan** [comment]
I think, I have figures this out. Here is the updated code. Please, correct. Thank you. We need to change the following line

`images = vae.decode(torch.Tensor(latent_spaces).to(device))`

to 

`images, states = vae.decode(torch.Tensor(latent_spaces).to(device))`

Thank you.

**Comment by masato-ka** [comment]
Thank you for your comment!
I'll fix this.

**Comment by abdul-mannan-khan** [comment]
OK. I have finiished training for 500 epochs. Next, I run `vae>viewer.ipynb`

After running the following block of the code
```
device = torch.device('cuda')
vae = VAE(image_channels=IMAGE_CHANNELS, z_dim=VARIANTS_SIZE)
vae.load_state_dict(torch.load(MODEL_PATH, map_location=torch.device(device)))
vae.to(device).eval()
```
I got the following error. 
```

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-1f8c07196d46> in <module>
      1 device = torch.device('cuda')
      2 vae = VAE(image_channels=IMAGE_CHANNELS, z_dim=VARIANTS_SIZE)
----> 3 vae.load_state_dict(torch.load(MODEL_PATH, map_location=torch.device(device)))
      4 vae.to(device).eval()

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1043         if len(error_msgs) > 0:
   1044             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1045                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1046         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1047 

RuntimeError: Error(s) in loading state_dict for VAE:
	Missing key(s) in state_dict: "decoder.7.weight", "decoder.7.bias". 
	Unexpected key(s) in state_dict: "out1.0.weight", "out1.0.bias", "out2.0.weight", "out2.0.bias". 
```

I think that vae.torch file is not properly generated by` VAE_CNN.ipynb`. Could you please check the problem with `VAE_CNN.ipynb` ? Thank you so much for your efforts.

**Comment by abdul-mannan-khan** [comment]
OK. Never mind again. I solved the problem. Just change the line in `vae_viewer.ipynb` from 

`vae.load_state_dict(torch.load(MODEL_PATH, map_location=torch.device(device)))`

to 

`vae.load_state_dict(torch.load(MODEL_PATH, map_location=torch.device(device)),strict=False)`

Now, it is working. Thank you.

**Comment by abdul-mannan-khan** [comment]
@masato-ka, I am still having an error in `vae_viewer.ipynb`. The error I am having is this 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-6d4c92d762e8> in <module>
     20     bce_result.value = m_vae_loss.item()
     21 
---> 22 vae_process({'new': camera.value})
     23 camera.observe(vae_process, names='value')

<ipython-input-8-6d4c92d762e8> in vae_process(change)
      5     image = torch.unsqueeze(image, dim=0).to(device)
      6     z, _ ,_ = vae.encode(image)
----> 7     reconst, sigma = vae.decode(z)
      8     to_visualize = torch.squeeze(reconst).detach().cpu().numpy()
      9     to_visualize = np.transpose(np.uint8(to_visualize*255),[1,2,0])[:,:,::-1]

ValueError: not enough values to unpack (expected 2, got 1)
```
as described there the  error is in `reconst, sigma = vae.decode(z)`, the problem is: `not enough values to unpack (expected 2, got 1)`

Could you please have a look? Thank you.

**Comment by masato-ka** [comment]
Are you re-install latest version ? 
Please test this debug code in the cell. and tell me result.
'''
6     z, _ ,_ = vae.encode(image)
7     ret = vae.decode(z)
       print(ret)
'''

In addition, I found some bug. I'll fix those bug in this weekend.

Wow! But I am told that only group tours enter the Japan. Could you visit to Tokyo ? I have a baby coming in February and it is difficult to move to Nagoya.
>By the way, I am planning a visit to Nagoya, Japan in 28 - 31 August, 2022. Would you have some time? I wish we could have a meeting.

**Comment by abdul-mannan-khan** [comment]
Oh. I just checked. Yes. I was using V1.6.0. I tried to update it but I was having issue using donkey-car repository. So, I have refreshed my Jetson Nano's SDK. I shall update you after installing V1.7.0. 

Thank you for your reply.

**Comment by masato-ka** [comment]
No, No, No If you use v1.6.0, please use v1.6.0 notebook. you can easily access from branch.

**Comment by abdul-mannan-khan** [comment]
> Wow! But I am told that only group tours enter the Japan. Could you visit to Tokyo ? I have a baby coming in February and it is difficult to move to Nagoya.

I am sorry for the late notice. Congratulations on your baby. Is it your first baby?  I shall visit Tokyo. I am coming with my sons and wife on a tour. I wish we could have a meeting. Would it be possible for you? Thank you. 

Regarding, racer, it took me some time to fix things here and there to install the new version. You were right. I did not get this error 

> ValueError: not enough values to unpack (expected 2, got 1)

I shall further test it on Monday. Thank you for your help.

**Comment by masato-ka** [comment]
I was released v1.7.1 please update your Jetracer. However you don't need flush SD Card.
Please uninstall python module by below command.
$pip3 uninstall learning_racer

**Comment by abdul-mannan-khan** [comment]
OK. I shall try installing v1.7.1. However, I used previous version and tried using `vae_viewer.ipynb`. Gladly, the previous error was removed as mentioned here 

> RuntimeError: Error(s) in loading state_dict for VAE:
> 	Missing key(s) in state_dict: "decoder.7.weight", "decoder.7.bias". 
> 	Unexpected key(s) in state_dict: "out1.0.weight", "out1.0.bias", "out2.0.weight", "out2.0.bias".

However, I did not get good matching. For reference I have attached my video. 


https://user-images.githubusercontent.com/22067958/177240429-20d33866-c900-4314-8a06-c0de86319410.mp4



I shall try tomorrow with v1.7.1. Thank you for providing this version.

**Comment by abdul-mannan-khan** [comment]
I tired it with version 1.7.1. It is still not able to correctly match. Here is today's video with v1.7.1

https://user-images.githubusercontent.com/22067958/177249256-3674b402-aba4-4eaa-a215-42b89ff34950.mp4

**Comment by masato-ka** [comment]
The course does not appear to be laid without wrinkles on the floor.
After the course has been set up nicely, run it along the center of the course with the radio controller while acquiring data.

**Comment by abdul-mannan-khan** [comment]
Thank You @masato-ka . I collected data again and trained it for 200 epochs. After that I noticed that it was slow and that's the response I got after almost 20 minutes. 

https://user-images.githubusercontent.com/22067958/177505507-7f0c7d3c-652a-4eb6-8d14-d6d1ec190b12.mp4

Also, I tried running `racer train -robot jetracer` and I got the following error 

`2022-07-06 17:28:14,700 - learning_racer.commands.subcommand - ERROR - :load_class:module 'learning_racer.teleoperate' has no attribute 'Teleoperation'`

Could you please have a look? Thank you.

**Comment by masato-ka** [comment]
* Please Shutdown all kernel in Jupyternoteboot before run notebook.
https://www.youtube.com/watch?v=tOjequ-46Qc

* Please update config.yml 
teleoperator: 'learning_racer.teleoperate:Teleoperation' 
to 
teleoperator: 'learning_racer.teleoperate:Teleoperator'

**Comment by abdul-mannan-khan** [comment]
I tried it and here is the output. 

https://user-images.githubusercontent.com/22067958/177706808-53d6c439-acc2-4388-b63d-b7dafacaf154.mp4

Also, I am facing error following error 

`2022-07-07 15:33:38,076 - learning_racer.commands.subcommand - ERROR - :load_pure_env:Could not initialize camera.  Please see error trace.`
It was working perfectly fine with previous version. Also, I noticed that the JetRacer executing commands significantly slower than before. Does it have to do something with version. I installed all the required tools like gym, stablebaselines3 etc separately as all those versions in default mode were giving errors.

**Comment by masato-ka** [comment]
The error is hardware problem(e.g. the cable is broken) or other process are using camera.

**Comment by abdul-mannan-khan** [comment]
I checked the hardware. It is fine. I think the problem was with stablebaseline3 version and its compatibility with OpenCV. So, I removed it and installed a compatible version. However, I am still getting similar response. 

https://user-images.githubusercontent.com/22067958/178426761-eb053284-3c54-4a55-94a0-84bb60990226.mp4

I think this algorithm is having problem in detection yellow line. I shall try with black lines now. Let's see what comes out.

**Comment by abdul-mannan-khan** [comment]
After so many different tries, finally, I am getting good response here 
![vae_response](https://user-images.githubusercontent.com/22067958/179439497-92f6001f-ce71-4f3b-a723-7e23cb46f772.png)

Here is my detail. I first removed the pink tint using 
> https://jonathantse.medium.com/fix-pink-tint-on-jetson-nano-wide-angle-camera-a8ce5fbd797f

Then, I used black tape to hilight the contrast, next I collected 15,000 pictures by putting JetRacer randomly on the track. Next, I trained th model using google colab for 200 epochs. 

Thank you @masato-ka for your help. Your constant support helped me fix this problme.  

In the next step, I am working on training. Currently, I have conducted tests for about 30 episodes and JetRacer is still not able to take turn. I am starting JetRacer just behind the turn and it usually goes off the black line. Also, training is taking long time.

**Comment by abdul-mannan-khan** [comment]
I have tried for training 128 episodes. It took me about 8 hours but after that the robot has stopped moving. Here is the last response I had
![Screenshot from 2022-07-19 14-34-58](https://user-images.githubusercontent.com/22067958/179682640-0b7edf6b-a877-4212-9ec8-ff40a750897f.png)

I also noticed that I get 0 fps. Is it suppose to be? Thank you for you help @masato-ka

**Comment by masato-ka** [comment]
This is reaching timesteps limit. Nothing output end of learning. please check timestep(default 5000).
If you need more timestep,  add --steps option to racer train command.
for example $ racer train --steps 10000

In addition
1.  I think 128 episode not need 8 hours. Did Jetson Nano set to 10W mode?
2. Please change some value of config.yml to below. It is training efficiently.
```
GRADIENT_STEPS: 100
USER_SDE: false
```
3. The timing to press the stop button is before going off course. Press the button when the front wheel is just above the line.

Already implements auto stop function. But it is experimental and buggy for Jetracer. It is makes learning easier.

**Comment by abdul-mannan-khan** [comment]
Hey @masato-ka 

I tried it many times but here is the response of the car. 

https://user-images.githubusercontent.com/22067958/180733720-56014e4b-ff39-4e48-802b-d24bba51c5f5.mp4

Here is my `cfg.yaml` file setting 
```
SAC_SETTING:
  LOG_INTERVAL: 1
  VERBOSE: 1
  LEARNING_RATE: 3e-4
  ENT_COEF: 'auto_0.1'
  TRAIN_FREQ: 1
  BATCH_SIZE: 64
  GRADIENT_STEPS: 200
  LEARNING_STARTS: 300
  BUFFER_SIZE: 30000
  VARIANTS_SIZE: 32
  IMAGE_CHANNELS: 3
  GAMMA: 0.99
  TAU: 0.02
  USER_SDE_AT_WARMUP: true
  USER_SDE: false
  SDE_SAMPLE_FREQ: 64



  #HyperParameter for Reward
REWARD_SETTING:
  REWARD_CRASH: -10
  CRASH_REWARD_WEIGHT: 5
  THROTTLE_REWARD_WEIGHT: 0.1

#AGENT_SETTING:
#  # Agent settings
#  N_COMMAND_HISTORY: 10
#  MIN_STEERING: -1.0
#  MAX_STEERING: 1.0
#  MIN_THROTTLE: 0.3
#  MAX_THROTTLE: 0.5
#  MAX_STEERING_DIFF: 0.15

#s#JetBot Reference
#AGENT_SETTING:
#  N_COMMAND_HISTORY: 10
#  MIN_STEERING: -0.5
#  MAX_STEERING: 0.5
#  MIN_THROTTLE: 0.3
#  MAX_THROTTLE: 0.5
#  MAX_STEERING_DIFF: 0.05

AGENT_SETTING:
  # Agent settings
  N_COMMAND_HISTORY: 20
  MIN_STEERING: -1.0
  MAX_STEERING: 1.0
  MIN_THROTTLE: 0.20 # 0.4
  MAX_THROTTLE: 0.23 # 0.9
  MAX_STEERING_DIFF: 0.9 #0.35

JETRACER_SETTING:
  STEERING_CHANNEL: 1
  THROTTLE_CHANNEL: 0
  STEERING_GAIN: 0.75
  THROTTLE_GAIN: 0.8

VAE_AUTO_STOP:
  VAE_AUTO_STOP: true
  VAE_AUTO_STOP_THRESHOLD: 4000
```
I tried running setup using 10000

`racer train -robot jetracer -steps 15000`

but it was not converging. I believe that road is not wide enough so there is a little room for the mistake and before the car could correct the path, it was out of the line. This is my understanding. Do you have any suggestion please? Thank you.

**Comment by masato-ka** [comment]
Your machine following straight !

My suggestion is
1. try reducing the maximum speed.
2. try starting the next episode from where you left off without returning to the starting point.

**Comment by abdul-mannan-khan** [comment]
Oh, finally I did it. 

https://youtu.be/B6RS8zxsd6I

I slowed down the speed and trained the algorithm for  20000 steps using the following command

`racer train -robot jetracer -steps 20000`

Thank you so much @masato-ka . I want to present this in a seminar. Would you be OK, if I acknowledge your help?

**Comment by abdul-mannan-khan** [comment]
Hello @masato-ka . I appreciate your help and really grateful to you. I have one last question. Now, as my car is trained, how can I save that training so that I don't have to train it again? Also, what can we do next after that? Could you share any of your ideas? Thank you so much.
