### ISSUE TITLE
How to control donkey car at donkey simulator?

### ISSUE THREAD

**Issue by gwiheo** [masato-ka/airc-rl-agent#41]
After running the following command, Donkey car appeared at simulator window with track on the left window.
$ racer train -robot sim -vae vae-gt-30K-150.torch -device cpu -host 127.0.0.1 -port 9091
Then it start to drive forward on the road, but I could not control the car. I tried to press arrow keys on the keyboard and other keys, but all the tries did not work. How can I control the car for training on the track?

**Comment by masato-ka** [comment]
It's normal behavior. You dosen't need to control agent. The agent learn automatically.
 Now simulator mode have a bug. Please reference #33 issue.

**Comment by gwiheo** [comment]
@masato-ka Thanks a lot. Now it works. I am happy to see the donkey car is driving automatically after RL training.

**Comment by masato-ka** [comment]
OK, sounds good. I close this issue.
